// <auto-generated />
using System;
using InstagramBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InstagramBot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InstagramBot.Models.Conversation", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("InstagramUserId").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<DateTime>("LastMessageAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("StartedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("TenantId").HasColumnType("uuid");
                b.Property<string>("UserName").HasMaxLength(200).HasColumnType("character varying(200)");
                b.HasKey("Id");
                b.HasIndex("TenantId", "InstagramUserId");
                b.ToTable("Conversations");
            });

            modelBuilder.Entity("InstagramBot.Models.Message", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Content").IsRequired().HasColumnType("text");
                b.Property<Guid>("ConversationId").HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("InstagramMessageId").HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<bool>("IsFromUser").HasColumnType("boolean");
                b.HasKey("Id");
                b.HasIndex("ConversationId");
                b.ToTable("Messages");
            });

            modelBuilder.Entity("InstagramBot.Models.Tenant", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("AccessToken").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                b.Property<string>("BusinessName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("CurrentMonthMessages").HasColumnType("integer");
                b.Property<string>("FallbackMessage").HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.Property<string>("InstagramPageId").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<string>("KnowledgeBase").IsRequired().HasColumnType("text");
                b.Property<int>("MonthlyMessageLimit").HasColumnType("integer");
                b.Property<string>("SystemPrompt").IsRequired().HasMaxLength(4000).HasColumnType("character varying(4000)");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("WelcomeMessage").HasMaxLength(1000).HasColumnType("character varying(1000)");
                b.HasKey("Id");
                b.HasIndex("InstagramPageId").IsUnique();
                b.ToTable("Tenants");
            });

            modelBuilder.Entity("InstagramBot.Models.Conversation", b =>
            {
                b.HasOne("InstagramBot.Models.Tenant", "Tenant")
                    .WithMany("Conversations")
                    .HasForeignKey("TenantId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Tenant");
            });

            modelBuilder.Entity("InstagramBot.Models.Message", b =>
            {
                b.HasOne("InstagramBot.Models.Conversation", "Conversation")
                    .WithMany("Messages")
                    .HasForeignKey("ConversationId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
                b.Navigation("Conversation");
            });

            modelBuilder.Entity("InstagramBot.Models.Conversation", b =>
            {
                b.Navigation("Messages");
            });

            modelBuilder.Entity("InstagramBot.Models.Tenant", b =>
            {
                b.Navigation("Conversations");
            });
        }
    }
}
